# Browsersync config
BROWSERSYNC:
  # URL of local development server goes here (ex. http://localsite.dev)
  url: "http://createit.local"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/bootstrap/scss"
    - "node_modules/slick-carousel/slick"
    - "node_modules/@fancyapps/fancybox/dist"
    - "node_modules/animate.css"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"
